### PR TITLE
Make old parameters optional and  fix ICompute model to support autostar...

### PR DESCRIPTION
**Pull request by deemoowoor**
...t parameter to simplify design (OMS-200)

### CODE REVIEW

**Comment by livenson** [comment]
Hm, this is not a complete task. Root password is never propagated. It would be nice to have it in a transient field though, i.e. never persisted in ZODB.

**Comment by livenson** [comment]
Hm, I'm getting a weird case (might be unrelated to this commit though), that if I click on the 'start vm' button right after the vm creation (once it's reached IDeployed state), it's giving me:

```
2013-02-15 19:16:50+0300 [httprest] Unhandled Error
    Traceback (most recent call last):
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 576, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1127, in gotResult
        _inlineCallbacks(r, g, deferred)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1069, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
    --- <exception caught here> ---
      File "/opt/omanagement/opennode/oms/endpoint/httprest/root.py", line 129, in _render
        ret = yield self.handle_request(request)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/python/threadpool.py", line 172, in _worker
        result = context.call(ctx, function, *args, **kwargs)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 118, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/opt/omanagement/eggs/Twisted-12.3.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 81, in callWithContext
        return func(*args,**kw)
      File "/opt/omanagement/opennode/oms/zodb/db.py", line 196, in run_in_tx
        result = fun(*args, **kwargs)
      File "/opt/omanagement/opennode/oms/endpoint/httprest/root.py", line 238, in handle_request
        res = renderer(request)
      File "/opt/omanagement/opennode/oms/endpoint/httprest/view.py", line 63, in render_PUT
        form.apply()
      File "/opt/omanagement/opennode/oms/model/form.py", line 173, in apply
        self.tmp_obj.apply()
      File "/opt/omanagement/opennode/oms/model/form.py", line 221, in apply
        setattr(self.__dict__['obj'], name, value)
    exceptions.AttributeError: can't set attribute
```

**Comment by livenson** [comment]
Yep, 100% reproducible. HTTP request is:

```
{
"tags":["state:inactive","arch:centos","virt_type:openvz","arch:linux","virt:yes","arch:x86_64","type:compute"],
"architecture":["x86_64","linux","centos"],
"cpu_info":"Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz",
"os_release":"build 35",
"kernel":"unknown",
"template":"opennode-oms",
"hostname":"aaa",
"ipv4_address":"192.168.0.1",
"ipv6_address":"::/128",
"state":"active",
"num_cores":1,
"memory":512,
"network":12500000,
"swap_size":4192,
"features":["ICompute","IDisplayName","IVirtualCompute","IMarkable","IDeployed","IInHangar"],
"diskspace":{"total":11264,"/":11264},"id":"3ad28666-9642-4aef-a04c-a73b21c68897"}

```

Although it's currently implemented in a somewhat unintuitive way - PUT'ting the desired state of a compute - it's somewhat complicated to rewrite this atm and anyway it should be an allowed operation on KNOT.

**Comment by livenson** [comment]
After ONC refresh, and VMlist reload, this operation actually succeeds. Which indicates a certain variable is not filtered out by KNOT's view. A new request's body looks like this:

```
{
"tags":["state:inactive","arch:centos","virt_type:openvz","arch:linux","virt:yes","arch:x86_64","type:compute"],
"architecture":["x86_64","linux","centos"],
"cpu_info":"Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz",
"os_release":"build 35",
"kernel":"unknown",
"template":"opennode-oms",
"hostname":"aaa",
"ipv4_address":"192.168.0.1/24",
"ipv6_address":"::/128",
"state":"active",
"num_cores":1,
"memory":512,
"network":12500000,
"swap_size":4192,
"features":["ICompute","IDisplayName","IVirtualCompute","IMarkable","IDeployed","IInHangar"],
"diskspace":{"total":11264,"/":11264},"id":"3ad28666-9642-4aef-a04c-a73b21c68897"}
```

**Comment by livenson** [comment]
Wierd, that the next request is exactly the same.

**Comment by deemoowoor** [comment]
Can't reproduce and I don't think it's related to this changeset.

**Comment by livenson** [comment]
Ok, merging, if persists - separate task.

**Pull request merged**
