### PR TITLE
Fix action implementation re to branch oms-133-2 in opennode-management ...

### PR DESCRIPTION
**Pull request by deemoowoor**
...(OMS-133)

### CODE REVIEW

**Comment by livenson** [comment]
Couldn't parse commit message - what does it mean?

**Comment by deemoowoor** [comment]
Under "re" I meant "related", although I just realized that usually it means 'regarding'. I will correct it.

**Comment by deemoowoor** [comment]
Umm, it actually depends on changes in opennode-management@oms-133-2, so we better merge this after that one.

**Comment by livenson** [comment]
hm, quite late for that

**Comment by deemoowoor** [comment]
Then we should consider merging that too. :)

**Pull request merged**
